### ISSUE TITLE
Blame Mode (Log who sent what)

### ISSUE THREAD

**Issue by Ryuno-Ki** [c3subtitles/L2S2#3]
Aka Blame mode :)

It would be handy to see in the hindsight, which line was written by whom.
A coloured indicator would be sufficient.

Important: It should not be deployed to consumers (projector, mobile app etc.).

**Comment by percidae** [comment]
I would also like to have that in the logs for the following reasons:
On the congress I am not able to be everywhere, so if I receive complaints about non accurate or bad subtitles in any way, I need to be able to check who caused and why. Or if it was a missunderstanding or sth else.
I need this to have a tool for quality assurances, since there were complaints which I could not confirm because I hadn't seen that talk myself.

Quality assurance will be an important topic for next congress. We need to have a focus on that - and also the tools and possibilities for it.

**Comment by Ryuno-Ki** [comment]
Bummer, SubRip [does not support comments](http://www.matroska.org/technical/specs/subtitles/srt.html).

I would like to get @luto into this thread, since he wrote a [converter](luto/c3subtitles-srt-converter) which could be adjusted to strip away metadata (here: writer). This way, we can simply add the writer information to the logline and get it stripped away afterwards.

**Comment by percidae** [comment]
So far I have unfortunately not have had any real use of the converter. Which means this part has no priority.
I can still convert the live-subs to normal plain text mode via import in a spreadsheet as "seperated values" and get rid of the timestamps and usernames that way pretty simple.

This is the best start for a transcript because you can move the lines around just as you like - my personal experience and as far as I heard also from others.

So maybe:
Timestamp <tab> Username: <tab>Live-Text
