### ISSUE TITLE
Multiline subtitles

### ISSUE THREAD

**Issue by Ryuno-Ki** [c3subtitles/L2S2#40]
For reference:

https://twitter.com/cellx/status/549234721826562048

cellx is asking for multiline subtitles. Especially when viewing online (instead of in the hall) the font size is too big.

Since I have not that huge experience, I'd like to hear @percidae PoV.

**Comment by percidae** [comment]
The subtitles in the webplayer were not just on line, this was depending on the amount of characters. But the area to display it in stayed the same no matter how many characters were transmitted.

Unfortuantely I think this is sth they have to fix in the webplayer, but the problem is actually known.
I will communicate that into that direction.

**Comment by MaZderMind** [comment]
You can open an issue in the new Streaming-Website-Repo: https://github.com/voc/streaming-website - it will be the base for 32C3 and all the events inbetween.
